### ISSUE TITLE
Weird behaviour on admin page

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-docs-starter#22]
The first time I land on the admin page, I see this:
<img width="1291" alt="Screen Shot 2022-01-24 at 9 26 14 AM" src="https://user-images.githubusercontent.com/3323181/150791266-fa7f7884-7fd8-4d27-80b7-07400440939a.png">

It says I'm logged in, but there's a login with Tina cloud button. Clicking the "Login with Tina Cloud" button seems to take me out of edit-mode, and slightly adjusts the layout of the page
<img width="1288" alt="Screen Shot 2022-01-24 at 9 26 24 AM" src="https://user-images.githubusercontent.com/3323181/150791403-7c634108-1257-4c20-99de-c9908ccd68a8.png">

**Comment by logan-anderson** [comment]
@jamespohalloran I think this admin page can be removed in favor of `tinaAdmin`.

Login: `/admin`
Logout: `/admin/logout`

**Comment by jamespohalloran** [comment]
I think you might have already solved this for the most part with https://github.com/tinacms/tina-docs-starter/pull/24/files#diff-76fd45f1e5562b12de01976eccb15df89219871d9052e39710bbea551e6c3088
Closing for now, and we'll re-update once the latest version of the admin is ready
