### ISSUE TITLE
Permanent redirects are annoying for local development

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-docs-starter#8]
The [permanent redirects](https://github.com/tinacms/tina-docs-starter/blob/main/next.config.js#L2) for `/` and `/docs/` are remembered by the browser, so working on other projects at `http://localhost:3000` results in a redirect to non-existing content.

**Comment by perkinsjr** [comment]
👍  agreed we put this in place for a temp fix. I can change to a temp redirect.

**Comment by perkinsjr** [comment]
Fixed updated.
